services:

  gotify:
    image: gotify/server:latest     # gotify/server-arm7
    container_name: Gotify
    ports:
      - "8008:80"
    restart: unless-stopped  
    environment:
      - GOTIFY_DEFAULTUSER_NAME=User
      - GOTIFY_DEFAULTUSER_PASS=p4ssw0rd
      - TZ=Europe/Madrid
    volumes:
      - ./data:/app/data
      
